buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}
plugins {
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
}
apply plugin: 'org.spongepowered.mixin'

group = mod_group_id
version = mod_version

base {
    archivesName = mod_id
}

java {
    sourceCompatibility = '17'
    targetCompatibility = '17'
}


minecraft {
    mappings channel: mapping_channel, version: mapping_version

    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'REGISTRIES'

            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            // Comma-separated list of namespaces to load gametests from. Empty = all namespaces.
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            //args '--nogui'
        }

        gameTestServer {
            property 'forge.enabledGameTestNamespaces', mod_id
        }

        data {
            workingDirectory project.file('run-data')

            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}
mixin {
    config "${mod_id}.mixins.json"
}
sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven {
        name = "Progwml6's maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        url 'https://maven.blamejared.com'
    }
    mavenCentral()
    maven{
        name = "SimpleMavenRepo"
        url = "https://raw.githubusercontent.com/yiyuyan/SimpleMavenRepo/refs/heads/master/"
    }
}

jarJar.enable()
dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    compileOnly fg.deobf("mezz.jei:jei-1.20.1-common-api:15.20.0.112")
    compileOnly fg.deobf("mezz.jei:jei-1.20.1-forge-api:15.20.0.112")
    runtimeOnly fg.deobf("mezz.jei:jei-1.20.1-forge:15.20.0.112")
    implementation 'org.tomlj:tomlj:1.1.0'

    implementation fg.deobf("gd.rf.kongzhongtitian:PipeAPI:1.20.1forge-1.0.11")
    implementation fg.deobf("gd.rf.kongzhongtitian:RecipesAPI:1.20.1forge-1.1.1")

    jarJar("gd.rf.kongzhongtitian:PipeAPI:[1.20.1forge-1.0.11,)")
    jarJar("gd.rf.kongzhongtitian:RecipesAPI:[1.20.1forge-1.1.1,)")

    runtimeOnly fg.deobf("cn.ksmcbrigade:mcmod-doll:1.0")

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

tasks.named('compileJava', JavaCompile) {
    options.annotationProcessorPath = configurations.annotationProcessor
    options.compilerArgs += [
            '-AdefaultObfuscationEnv=searge',
            '-AmappingTypes=tsrg'
    ]
}

jar {
    manifest {
        attributes([
                "MixinConfigs": "ducktech.mixins.json"
        ])
    }
}

jar {
    manifest {
        attributes([
                "MixinConfigs": "ducktech.mixins.json"
        ])
    }
}

tasks.named('processResources', ProcessResources).configure {


    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
    }
}

tasks.named('jar', Jar).configure {
    manifest {

    }

    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}