modLoader = "javafml"
loaderVersion = "[47,)"
license = "BSD-3-Clause-Clear"
issueTrackerURL="https://github.com/kongzhongtitians/DuckTech/issues"
[[mods]]
modId = "ducktech"
version = "0.0.0"
displayName = "DuckTech"
displayURL="https://kongzhongtitians.github.io/intro/ducktech/home.html"
logoFile="logo.png"
authors = "The Duck Team"
description = '''DuckTech'''
[[dependencies."ducktech"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies."ducktech"]]
modId = "jei"
mandatory = false
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies."ducktech"]]
modId = "recipesapi"
mandatory = true
versionRange = "[1.1.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."ducktech"]]
modId = "pipe_api"
mandatory = true
versionRange = "[1.0.5,)"
ordering = "NONE"
side = "BOTH"